Don't exit when asdf plugin already installed
Related to
- https://github.com/asdf-vm/asdf/issues/659
- https://github.com/asdf-vm/asdf/pull/688

Note that `asdf install` may soon also return a non-zero code [1] which
would require a similar patch in these language scripts.

[1]: https://github.com/asdf-vm/asdf/issues/747

diff --git a/languages/elixir b/languages/elixir
--- a/languages/elixir
+++ b/languages/elixir
@@ -3,8 +3,12 @@
 source utils.sh
 
 # Elixir requires that Erlang be installed.
-asdf plugin-add erlang
-asdf plugin-add elixir
+asdf plugin-add erlang && erlang_status=$? || erlang_status=$?
+asdf plugin-add elixir && elixir_status=$? || elixir_status=$?
+
+# `asdf plugin-add` returns exit code 2 when plugin already installed, but it's not an error.
+[[ $erlang_status -ne 0 && $erlang_status -ne 2 ]] && exit $erlang_status
+[[ $elixir_status -ne 0 && $elixir_status -ne 2 ]] && exit $elixir_status
 
 if brew --prefix openssl > /dev/null; then
   export ERLANG_OPENSSL_PATH="$(brew --prefix openssl)"
diff --git a/languages/ruby b/languages/ruby
--- a/languages/ruby
+++ b/languages/ruby
@@ -10,6 +10,10 @@ if brew --prefix openssl > /dev/null; then
   export RUBY_CONFIGURE_OPTS="$RUBY_CONFIGURE_OPTS --with-openssl-dir=$(brew --prefix openssl)"
 fi
 
-asdf plugin-add ruby
+asdf plugin-add ruby && status=$? || status=$?
+
+# `asdf plugin-add` returns exit code 2 when plugin already installed, but it's not an error.
+[[ $status -ne 0 && $status -ne 2 ]] && exit $status
+
 asdf install ruby latest
 asdf global ruby $(asdf latest ruby)
